stages:
  - build
  - test
  - release
  - deploy

include:
  - local: .gitlab/*.gitlab-ci.yml

variables:
  SLACKCAST_TEST_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  SLACKCAST_RELEASE_IMAGE_NAME: $CI_REGISTRY_IMAGE:latest

build:gitlab:test:
  stage: build
  extends: [".kaniko:build"]
  variables:
    KANIKO_IMAGE_NAME: $SLACKCAST_TEST_IMAGE_NAME
    RAILS_ENV: "test"
  only: ["merge_requests"]
  needs: []
  dependencies: []

rspec:
  stage: test
  image: $SLACKCAST_TEST_IMAGE_NAME
  variables:
    SLACK_API_TOKEN: 'foobar'
    AIRBRAKE_PROJECT_ID: 'DUMMY'
    AIRBRAKE_PROJECT_KEY: 'DUMMY'
  script:
    - bundle exec rspec -f doc -r rspec_junit_formatter -f RspecJunitFormatter -o rspec.xml
  artifacts:
    reports:
      junit: rspec.xml
  needs: ["build:gitlab:test"]
  dependencies: ["build:gitlab:test"]
  only: ["merge_requests"]

release:gitlab:
  stage: release
  extends: [".kaniko:build"]
  variables:
    KANIKO_IMAGE_NAME: $SLACKCAST_RELEASE_IMAGE_NAME
    RAILS_ENV: "production"
  only: ["master"]
  needs: ["rspec"]
  dependencies: ["rspec"]

deploy:
  stage: deploy
  image: $CONTAINER_RELEASE_IMAGE
  variables:
    APP_NAME: 'slackcast'
  script:
    - bundle exec dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_API_KEY
  only: ["master"]
  needs: ["release:gitlab"]
  dependencies: ["release:gitlab"]
