version: '3.6'

volumes:
  redis:

services:
  app:
    build: .
    image: registry.gitlab.com/mixlr/slackcast
    stdin_open: true
    tty: true
    environment: &development
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/"
      LOG_LEVEL: "INFO"
    volumes:
      - .:/src/app

  web:
    extends:
      service: app
    command: bundle exec puma -C config/puma.rb
    environment:
      <<: *development
      PORT: '3001'
    ports:
      - '3001:3001'
    depends_on:
    - redis

  mick:
    extends:
      service: app
    command: bundle exec rails runner bin/mick
    environment:
      <<: *development
      SLACK_API_TOKEN:
      DROPBOX_API_TOKEN:
      DROPBOX_ROOT_PATH:
    depends_on:
      - redis

  redis:
    image: redis:6.2.3
    volumes:
      - redis:/data
    expose:
      - 6379
